import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import {
  INITIAL_USERS, INITIAL_ROLES, INITIAL_PATIENTS, INITIAL_REGISTRATIONS, INITIAL_GENERAL_CONSENTS,
  INITIAL_MEDICAL_RECORDS, INITIAL_CPPT, INITIAL_INFORMED_CONSENTS, INITIAL_CODING, INITIAL_CLAIMS,
  INITIAL_BILLING, INITIAL_BEDS, INITIAL_DOKUMEN_BERKAS, INITIAL_RESUME_MEDIS,
} from '../src/data/mockData';
import { buildTodayRegistrations, sanitizeMedicalRecords, sanitizePatientList } from '../src/data/seedNormalizers';

export const TEMPLATE_CLASS_ID = '00000000-0000-0000-0000-000000000001';

export const sqlLiteral = (s: string) => `'${s.replace(/'/g, "''")}'`;

const textArray = (xs: string[]) => `array[${xs.map(sqlLiteral).join(',')}]::text[]`;

function rolesForSeed() {
  return INITIAL_ROLES.map(r => r.id === 'R03'
    ? { ...r, access: Array.from(new Set([...r.access.filter(a => a !== 'praktikum'), 'manajemenuser'])) }
    : r);
}

function insertRows(table: string, rows: { id: string }[]): string {
  if (rows.length === 0) return '';
  const values = rows
    .map(r => `  (${sqlLiteral(TEMPLATE_CLASS_ID)}, ${sqlLiteral(r.id)}, ${sqlLiteral(JSON.stringify(r))}::jsonb)`)
    .join(',\n');
  return `insert into public.${table} (class_id, id, data) values\n${values};\n`;
}

export function buildSeedSql(): string {
  const staff = INITIAL_USERS.map(({ password: _pw, ...u }) => u);
  const tables: [string, { id: string }[]][] = [
    ['staff_directory', staff],
    ['patients', sanitizePatientList(INITIAL_PATIENTS)],
    ['registrations', [...buildTodayRegistrations('__TODAY__', '__TODAYCOMPACT__'), ...INITIAL_REGISTRATIONS]],
    ['general_consents', INITIAL_GENERAL_CONSENTS],
    ['medical_records', sanitizeMedicalRecords(INITIAL_MEDICAL_RECORDS)],
    ['cppt', INITIAL_CPPT],
    ['informed_consents', INITIAL_INFORMED_CONSENTS],
    ['coding', INITIAL_CODING],
    ['claims', INITIAL_CLAIMS],
    ['billing', INITIAL_BILLING],
    ['beds', INITIAL_BEDS],
    ['dokumen_berkas', INITIAL_DOKUMEN_BERKAS],
    ['resume_medis', INITIAL_RESUME_MEDIS],
    ['asuhan_keperawatan', []],
  ];

  const roleValues = rolesForSeed()
    .map(r => `  (${sqlLiteral(r.id)}, ${sqlLiteral(r.name)}, ${textArray(r.access)})`)
    .join(',\n');

  return [
    '-- GENERATED by scripts/build-seed.ts from src/data/mockData.ts. Do not edit by hand; run `npm run seed:build`.',
    'begin;',
    "select set_config('simrs.skip_audit', 'on', true);",
    `insert into public.practice_roles (id, name, access) values\n${roleValues}\non conflict (id) do nothing;`,
    `insert into public.classes (id, name, is_template) values (${sqlLiteral(TEMPLATE_CLASS_ID)}, 'TEMPLATE (jangan dipakai)', true) on conflict (id) do nothing;`,
    ...tables.map(([t]) => `delete from public.${t} where class_id = ${sqlLiteral(TEMPLATE_CLASS_ID)};`),
    ...tables.map(([t, rows]) => insertRows(t, rows)),
    'commit;',
    '',
  ].join('\n');
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  writeFileSync('supabase/seed.sql', buildSeedSql());
  console.log('wrote supabase/seed.sql');
}
